"""harden expenses table

Revision ID: 78ba961490ba
Revises: 5161126f9243
Create Date: 2026-01-29 17:36:11.349016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ba961490ba'
down_revision: Union[str, Sequence[str], None] = '5161126f9243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_expenses_user_date', 'expenses', ['user_id', 'expense_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_expenses_user_date', table_name='expenses')
    # ### end Alembic commands ###
